"""initial production workspace schema

Revision ID: 74e3ca148483
Revises:
Create Date: 2026-08-24 02:04:20.723997
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '74e3ca148483'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_run_id'), 'agent_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_workspace_id'), 'agent_actions', ['workspace_id'], unique=False)
    op.create_table('canvas_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_events_workspace_id'), 'canvas_events', ['workspace_id'], unique=False)
    op.create_table('computation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('roots', sa.JSON(), nullable=False),
    sa.Column('computed', sa.JSON(), nullable=False),
    sa.Column('failed', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computation_runs_workspace_id'), 'computation_runs', ['workspace_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('edge_id', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_workspace_id'), 'edges', ['workspace_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_workspace_id'), 'exports', ['workspace_id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_workspace_id'), 'generation_runs', ['workspace_id'], unique=False)
    op.create_table('human_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_actions_workspace_id'), 'human_actions', ['workspace_id'], unique=False)
    op.create_table('module_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_versions_module_id'), 'module_versions', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_versions_workspace_id'), 'module_versions', ['workspace_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('module_id', sa.String(length=128), nullable=False),
    sa.Column('module_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'module_id', name='uq_workspace_module')
    )
    op.create_index(op.f('ix_modules_workspace_id'), 'modules', ['workspace_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_workspace_id'), 'plans', ['workspace_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_workspace_id'), 'requests', ['workspace_id'], unique=False)
    op.create_table('shares',
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_shares_workspace_id'), 'shares', ['workspace_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_workspace_id'), 'snapshots', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_workspace_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_shares_workspace_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_requests_workspace_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_plans_workspace_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_modules_workspace_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_module_versions_workspace_id'), table_name='module_versions')
    op.drop_index(op.f('ix_module_versions_module_id'), table_name='module_versions')
    op.drop_table('module_versions')
    op.drop_index(op.f('ix_human_actions_workspace_id'), table_name='human_actions')
    op.drop_table('human_actions')
    op.drop_index(op.f('ix_generation_runs_workspace_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_exports_workspace_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_edges_workspace_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_computation_runs_workspace_id'), table_name='computation_runs')
    op.drop_table('computation_runs')
    op.drop_index(op.f('ix_canvas_events_workspace_id'), table_name='canvas_events')
    op.drop_table('canvas_events')
    op.drop_index(op.f('ix_agent_actions_workspace_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_run_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
